name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      -
        name: Docker Pull & Run From Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_DNS}}
          username: ec2-user
          key: ${{secrets.ACTION_PRIVATE_KEY}}
          envs: GITHUB_SHA
          script: |
            sudo docker pull hsiehbing/clockbox:latest
            sudo docker kill test1
            sudo docker rm test1
            sudo docker run -d --name test1 -p 443:443 hsiehbing/clockbox:latest
       

